### ISSUE TITLE
Clarify "interchange molecular formats" in README.md

### ISSUE THREAD

**Issue by ben-albrecht** [rpmuller/chemxchange#1]
Hi @rpmuller -- I hope I'm not stepping on your toes by commenting on a brand-new repo, but I'm genuinely curious:

How will this project interchange molecular formats differently than the existing tools that strive to achieve this?

e.g.

- [cclib](https://github.com/cclib/cclib)
- [chemfiles](https://github.com/chemfiles/chemfiles)
- [openbabel](https://github.com/openbabel/openbabel)

Thanks!

**Comment by rpmuller** [comment]
Perhaps not at all different. Just playing with some ideas and some old
converter code I had sitting around. I'll put some notes in the README file
to point people to the other projects and explain this.
